on:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/rector-cs.yml'
      - 'composer.json'
      - 'rector.php'
      - '.php-cs-fixer.dist.php'

name: Rector + PHP CS Fixer

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rector:
    uses: yiisoft/actions/.github/workflows/rector-cs.yml@dev-rector-cs
    secrets:
      token: ${{ secrets.YIISOFT_GITHUB_TOKEN }}
    with:
      repository: ${{ github.event.pull_request.head.repo.full_name }}
      php: '8.4'
